version: '3'
services:
  app:
    container_name: app
    restart: always
    image: marcelofabianov/nestjs
    build:
      context: ./_docker/local/app
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - ./_docker/local/app/.zshrc:/home/node/.zshrc
    networks:
      - nest

networks:
  nest:
    driver: bridge
