version: '3'
services:
  app:
    container_name: app
    restart: always
    image: marcelofabianov/nestjs
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - .:/app
    networks:
      - nest

networks:
  nest:
    driver: bridge
